server:
  port: 9003
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/shopping?characterEncoding=utf8&serverTimezone=Asia/Shanghai
      username: root
      password: 520258
      max-active: 20
      max-wait: 6000
      min-idle: 1
      test-on-borrow: true
      test-on-return: true
  rabbitmq:
    host: 182.92.82.190
    port: 5672
    username: WeszTx
    password: EMXT5201314+    
  redis:
    database: 0
    host: 182.92.82.190
    port: 6379
    password: EMXT5201314+
    jedis:
      pool:
        max-active: 1
        max-wait: -1
        max-idle: 10
        min-idle: 2
    timeout: 1000      
      
mybatis:
  mapper-locations: classpath*:com/neuedu/mapper/*Mapper.xml
  config-location: classpath:mybatis-config.xml
  
timeout: 1000

order: 
 timeout: 1
